### PR TITLE
Update puppetagent_cron.erb

### PR DESCRIPTION
**Pull request by bryan-howard**
Fix redirection order to prevent unnecessary email to root.
[Hi Trevor, I work with Max Robinson at The Aerospace Corporation --Bryan Howard]

### CODE REVIEW

**Comment by trevor-vaughan** [comment]
Hi Byran,

Good catch!

Would you mind creating a ticket over at https://simp-project.atlassian.net and modifying your commit to have the ticket number in the header like (SIMP-XXX) Message?

If this is too much trouble, let me know and we can hack around it in Gerrit.

It looks like we might also need you to rebase this commit against the latest codebase since Gerrit wouldn't import it.

Thanks,

Trevor

**Comment by bryan-howard** [comment]
Trevor,

I seem to be failing here...

1) I don't see how to create a ticket in the SIMP JIRA instance mentioned above.

2) Assuming a ticket (SIMP-XXX), do I just mention that string in the commit message? Or is there something more?

3) I'm a little surprised about the need to rebase.  I forked the codebase moments before generating the pull request. And I only see one branch (master). Is the latest codebase somewhere else?

Thanks,

Bryan Howard

**Comment by lnemsick-simp** [comment]
This work was already completed.

**Comment by trevor-vaughan** [comment]
@bryan-howard I'm closing this as it got incorporated into a larger patch set (we did give you credit!)

Thanks for the patch!

**Pull request closed without merging**
