### PR TITLE
(SIMP-8958) Standardize assets in pupmod-simp-pupmod

### PR DESCRIPTION
**Pull request by op-ct**
This patch baselines the latest standardized assets for Puppet modules.

SIMP-9063 #close
[SIMP-8958] #comment Standardized assets in pupmod-simp-pupmod
[SIMP-8489] #comment Updated pupmod-simp-pupmod GLCI pipeline to Puppet 6.18
[SIMP-8923] #comment Renamed 'sanity' to 'releng' in pupmod-simp-pupmod
[SIMP-8984] #comment Updated pupmod-simp-pupmod to new GLCI conventions

[SIMP-8958]: https://simp-project.atlassian.net/browse/SIMP-8958
[SIMP-8489]: https://simp-project.atlassian.net/browse/SIMP-8489
[SIMP-8923]: https://simp-project.atlassian.net/browse/SIMP-8923
[SIMP-8984]: https://simp-project.atlassian.net/browse/SIMP-8984

### CODE REVIEW

**Review by lnemsick-simp — DISMISSED** [review]
init.pp has a check for `$facts['operatingsystemmajrelease'] < '7'

**Comment by lnemsick-simp** [comment]
I'll fix

**Comment by lnemsick-simp** [comment]
FIPS mode tests are failing because puppetserver RPM on EL8 is not signed appropriately for FIPS.

**Comment by trevor-vaughan** [comment]
The issue with the EL8 packages is being tracked as [PUP-10859](https://tickets.puppetlabs.com/browse/PUP-10859).

**Review by trevor-vaughan — APPROVED** [review]

**Comment by trevor-vaughan** [comment]
Going ahead and submitting this because the issues are outside of our control.

**Pull request merged**
